version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5433:5432'
    command: postgres -c max_connections=200
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=jmgcasd@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
